version: '3.4'

services:
  alarmservice:
    image: ${DOCKER_REGISTRY-}alarmservice
    build:
      context: .
      dockerfile: src/Services/AlarmService/Dockerfile
    networks:
        - rabbitmq_go_net

  homeownerservice:
    image: ${DOCKER_REGISTRY-}homeownerservice
    build:
      context: .
      dockerfile: src/Services/HomeOwnerService/Dockerfile
    networks:
        - rabbitmq_go_net


  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net


networks:
  rabbitmq_go_net:
    driver: bridge